Add SSH_ARGS environment variable
DBCDK/morph pull request #205
Opened 2023-05-25 08:26 UTC by gaykitty

This variable allows users to specify other custom arguments to be used with ssh and scp. This allows users to take advantage of more advanced ssh features like ControlPath, which could be used to fix #102 among other things.

2024-02-28 08:32 UTC, cafkafk requested changes
Could you fix the merge conflicts please, and then rebase this on top of the master branch?

2024-03-10 05:12 UTC, gaykitty commented
I rebased my changes and update the vendor hashes in default.nix and flake.nix, which I forgot last time.

2024-03-11 05:30 UTC, cafkafk requested changes
TIL about ControlPath and ControlMaster, this is cool :O

Code looks okay, and it doesn't seem to introduce any regressions. That said, I'm unsure how to use this, trying with `SSH_ARGS="-o ControlPath=~/.ssh/control-%h-%p-%r"` or `SSH_ARGS="-oControlPath=~/.ssh/control-%h-%p-%r"` both fail. 

Could you give me an example of usage? Also, perhaps adding this to the "Environment Variables" section of the README.md might be very helpful to make this feature discoverable.

2024-03-13 00:01 UTC, gaykitty commented
In the months since I opened this PR I've stopped using morph (I actually forgot I opened this PR). So I'm not sure how to test this as I don't have a server I'm managing with morph. I believe I tested using ControlPath at the time I wrote this PR but I don't remember that well. I do still use ControlPath in my current scripts though, maybe they could provide a useful reference on how to use it.

https://git.sr.ht/~zethra/turtle/tree/main/item/deploy.sh#L21

2024-03-13 10:09 UTC, srhb commented
Thanks!

This is not quite as trivial because of the difference in handling the different kind of options, ie. if you use both the hardcoded options and SSH_ARGS with "-o something"

Because each case is different in NIX_SSHOPTS and the pure command args, I think I much prefer using `SSH_CONFIG_FILE` for complex interactions here, as it will have fewer edge cases and work homogenously in both cases.

Using that, it's totally possible to use ControlMaster and friends today, and using `Include` in the actual file, you could compose it with the normal user config as well.

Closing.

2024-03-13 10:09 UTC, closed without merging