RFC: HTTP hooks for integrating morph deployments into existing infrastructure
DBCDK/morph pull request #84
Opened 2019-10-27 11:18 UTC by adamtulinius

This is really really rough and untested ideas, and probably waaay too ambitious, so don't panic :tm: (yet).

2020-09-30 23:46 UTC, blaggacao commented on rfcs/01-http-hooks.md
> +The most straightforward way of implementing hooks would be by executing a command and sending all required state as an argument to the command.
Would a task runner as repo driver such as `just` do?

2020-09-30 23:49 UTC, blaggacao commented on rfcs/01-http-hooks.md
> +The most straightforward way of implementing hooks would be by executing a command and sending all required state as an argument to the command.
maybe rather than implementing hooks, morph would expose events?
Benefit: is not really tied to a specific server implementation. Just consumers.

2020-09-30 23:50 UTC, blaggacao commented on rfcs/01-http-hooks.md
> +The most straightforward way of implementing hooks would be by executing a command and sending all required state as an argument to the command.
There is even an ideal candidate: https://cloudevents.io/

2020-09-30 23:54 UTC, blaggacao commented on rfcs/01-http-hooks.md
> +The most straightforward way of implementing hooks would be by executing a command and sending all required state as an argument to the command.
Other than that, I like the proposal! :+1:

2020-10-01 21:56 UTC, blaggacao commented
I do very much support this for being able to register node identity before an identity attestation service, but also to previously obtain node join token.

2020-10-01 22:10 UTC, blaggacao requested changes
I'd ask for a more standardized protocol mainly for the mentioned sdk reason.

2020-10-01 22:10 UTC, blaggacao commented on rfcs/01-http-hooks.md
> +}
Proposal use [cloud evens](https://github.com/cloudevents/spec#cloudevents-documents) &mdash; for example: https://github.com/cloudevents/spec/blob/v1.0/json-format.md

That way it's easy to consume those events with one of the available [sdks](https://github.com/cloudevents/spec#sdks).

2021-11-17 10:22 UTC, johanot commented
Closing this for now. Not because we don't want the feature, but rather because we don't have the capacity for maintaining and updating RFC's for now. We'd love to see a PR for morph hooks though!

2021-11-17 10:22 UTC, closed without merging